/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountGroup: typeof import('./src/components/accounts/AccountGroup.vue')['default']
    CategoryPicker: typeof import('./src/components/booking/CategoryPicker.vue')['default']
    DesktopLayout: typeof import('./src/components/layout/DesktopLayout.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ExpenseChart: typeof import('./src/components/stats/ExpenseChart.vue')['default']
    InsightCard: typeof import('./src/components/stats/InsightCard.vue')['default']
    MobileLayout: typeof import('./src/components/layout/MobileLayout.vue')['default']
    ModeSwitch: typeof import('./src/components/booking/ModeSwitch.vue')['default']
    NetWorthCard: typeof import('./src/components/accounts/NetWorthCard.vue')['default']
    NumberKeyboard: typeof import('./src/components/booking/NumberKeyboard.vue')['default']
    PinDialog: typeof import('./src/components/common/PinDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransferPanel: typeof import('./src/components/booking/TransferPanel.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
